language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt install protobuf-compiler
  - pip install -q tensorflow==2.0.0-beta1
  - pip install protobuf>=3.6.1
  - sh compile_proto.sh
# command to run tests
script:
  - python -m unittest discover -p "*_test.py"
